### PR TITLE
Added nuget packaging

### PR DESCRIPTION
**Pull request by semack**
The finish the PR the following new two secrets need to be installed
- NUGET_API_KEY 
- NUGET_SOURCE (set to "https://api.nuget.org/v3/index.json")

The new package build will automatically trigger by the push to master.

### CODE REVIEW

**Review by JeanCollas — APPROVED** [review]

**Comment by semack** [comment]
Great, thank you

**Comment by JeanCollas** [comment]
Any idea why the secrets are not taken into account ?
image

image

**Comment by semack** [comment]
Should take

**Comment by semack** [comment]
fork deleted

**Comment by semack** [comment]
You could gimme access ti the repo as member

**Comment by JeanCollas** [comment]
Fixed & granted

**Pull request merged**
